// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesiApi.Core.Data;

#nullable disable

namespace TesiAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616112504_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TesiApi.Core.Model.Apartments", b =>
                {
                    b.Property<int>("ApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("apartment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ApartmentID"));

                    b.Property<string>("ApartmentDetails")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("apartment_details");

                    b.Property<string>("ApartmentNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("apartment_no");

                    b.Property<int>("ApartmentSize")
                        .HasColumnType("int")
                        .HasColumnName("apartment_size");

                    b.Property<int>("ApartmentTypeID")
                        .HasColumnType("int")
                        .HasColumnName("apartment_type_id");

                    b.Property<int>("BathroomCount")
                        .HasColumnType("int")
                        .HasColumnName("bathroom_count");

                    b.Property<int>("BedroomCount")
                        .HasColumnType("int")
                        .HasColumnName("bedroom_count");

                    b.Property<decimal>("RentPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("rent_price");

                    b.Property<int>("SellerID")
                        .HasColumnType("int")
                        .HasColumnName("seller_id");

                    b.HasKey("ApartmentID");

                    b.HasIndex("ApartmentTypeID");

                    b.ToTable("apartments");
                });

            modelBuilder.Entity("TesiApi.Core.Model.RefApartmentTypes", b =>
                {
                    b.Property<int>("ApartmentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("apartment_type_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ApartmentTypeID"));

                    b.Property<string>("apartment_type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("apartment_type");

                    b.HasKey("ApartmentTypeID");

                    b.ToTable("ref_apartment_types");
                });

            modelBuilder.Entity("TesiApi.Core.Model.Apartments", b =>
                {
                    b.HasOne("TesiApi.Core.Model.RefApartmentTypes", "RefApartmentTypes")
                        .WithMany("Apartments")
                        .HasForeignKey("ApartmentTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RefApartmentTypes");
                });

            modelBuilder.Entity("TesiApi.Core.Model.RefApartmentTypes", b =>
                {
                    b.Navigation("Apartments");
                });
#pragma warning restore 612, 618
        }
    }
}
