// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesiApi.Core.Data;

#nullable disable

namespace TesiAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TesiApi.Core.Model.Accounts", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AccountID"));

                    b.Property<DateTime>("AccountCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("account_created");

                    b.Property<DateTime>("AccountEdited")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("account_edited");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("account_email");

                    b.Property<string>("AccountPassword")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasColumnName("is_deleted");

                    b.HasKey("AccountID");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("TesiApi.Core.Model.Apartments", b =>
                {
                    b.Property<int>("ApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("apartment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ApartmentID"));

                    b.Property<string>("ApartmentDetails")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("apartment_details");

                    b.Property<string>("ApartmentNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("apartment_no");

                    b.Property<int>("ApartmentSize")
                        .HasColumnType("int")
                        .HasColumnName("apartment_size");

                    b.Property<int>("ApartmentTypeID")
                        .HasColumnType("int")
                        .HasColumnName("apartment_type_id");

                    b.Property<int>("BathroomCount")
                        .HasColumnType("int")
                        .HasColumnName("bathroom_count");

                    b.Property<int>("BedroomCount")
                        .HasColumnType("int")
                        .HasColumnName("bedroom_count");

                    b.Property<decimal>("RentPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("rent_price");

                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("seller_id");

                    b.HasKey("ApartmentID");

                    b.HasIndex("ApartmentTypeID");

                    b.HasIndex("UserID");

                    b.ToTable("apartments");
                });

            modelBuilder.Entity("TesiApi.Core.Model.RefApartmentTypes", b =>
                {
                    b.Property<int>("ApartmentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("apartment_type_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ApartmentTypeID"));

                    b.Property<string>("apartment_type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("apartment_type");

                    b.HasKey("ApartmentTypeID");

                    b.ToTable("ref_apartment_types");
                });

            modelBuilder.Entity("TesiApi.Core.Model.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Address");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<int>("IsSeller")
                        .HasColumnType("int")
                        .HasColumnName("is_seller");

                    b.Property<int>("IsVerified")
                        .HasColumnType("int")
                        .HasColumnName("is_verified");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("SellerDetails")
                        .HasColumnType("longtext")
                        .HasColumnName("seller_details");

                    b.HasKey("UserID");

                    b.HasIndex("AccountID");

                    b.ToTable("users");
                });

            modelBuilder.Entity("TesiApi.Core.Model.Apartments", b =>
                {
                    b.HasOne("TesiApi.Core.Model.RefApartmentTypes", "RefApartmentTypes")
                        .WithMany("Apartments")
                        .HasForeignKey("ApartmentTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesiApi.Core.Model.Users", "Users")
                        .WithMany("Apartments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RefApartmentTypes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TesiApi.Core.Model.Users", b =>
                {
                    b.HasOne("TesiApi.Core.Model.Accounts", "Accounts")
                        .WithMany("Users")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("TesiApi.Core.Model.Accounts", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TesiApi.Core.Model.RefApartmentTypes", b =>
                {
                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("TesiApi.Core.Model.Users", b =>
                {
                    b.Navigation("Apartments");
                });
#pragma warning restore 612, 618
        }
    }
}
